"""Add phone number to users model

Revision ID: ced81a388227
Revises: a4694c363b86
Create Date: 2025-10-27 20:45:43.121973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ced81a388227'
down_revision = 'a4694c363b86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint("uq_users_phone_number", ['phone_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint("uq_users_phone_number", type_='unique')
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
