"""Adding user_badges.py model

Revision ID: e4a6c55556ec
Revises: a79b9a3a473c
Create Date: 2025-10-29 08:51:56.184439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4a6c55556ec'
down_revision = 'a79b9a3a473c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_badges',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('badge_id', sa.String(length=100), nullable=False),
    sa.Column('awarded_at', sa.DateTime(), nullable=True),
    sa.Column('event_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_badges')
    # ### end Alembic commands ###
