"""add onboarding column for orgs

Revision ID: e5eb684d52cd
Revises: e9734c1b9bd7
Create Date: 2025-10-30 15:57:12.604463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5eb684d52cd'
down_revision = 'e9734c1b9bd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_org_onboarded', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_org_onboarded')

    # ### end Alembic commands ###
